### ISSUE TITLE
clim_sim has no attribute 'force_cuda_rast'

### ISSUE THREAD

**Issue by Adamdad** [ashawkey/kiuikit#2]
```
(/local_home/yangxingyi/3dgs) yangxingyi@deep60:~/3dgs/threestudio$ python -m kiui.cli.clip_sim load/images/dog1_rgba.png outputs/gs-zero123-sai/256_dog1_rgba.png@20240105-054050/save/it1000-export/model.obj
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [02:20<00:00, 70.24s/it]
2024-01-05 05:58:25.128825: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /local_home/yangxingyi/3dgs/lib/python3.8/site-packages/cv2/../../lib64:
2024-01-05 05:58:25.147586: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-05 05:58:25.523789: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /local_home/yangxingyi/3dgs/lib/python3.8/site-packages/cv2/../../lib64:
2024-01-05 05:58:25.523864: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /local_home/yangxingyi/3dgs/lib/python3.8/site-packages/cv2/../../lib64:
2024-01-05 05:58:25.523873: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
preprocessor_config.json: 100%|█████████████████████████████████████████████████████████| 316/316 [00:00<00:00, 129kB/s]
tokenizer_config.json: 100%|████████████████████████████████████████████████████████████| 904/904 [00:00<00:00, 466kB/s]
[load_obj] init empty albedo!
[Mesh loading] v: torch.Size([15647, 3]), f: torch.Size([31415, 3])
[Mesh loading] vn: torch.Size([15647, 3]), fn: torch.Size([31415, 3])
[Mesh loading] vt: torch.Size([23479, 2]), ft: torch.Size([31415, 3])
Traceback (most recent call last):
  File "/local_home/yangxingyi/3dgs/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/local_home/yangxingyi/3dgs/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/local_home/yangxingyi/3dgs/lib/python3.8/site-packages/kiui/cli/clip_sim.py", line 63, in <module>
    gui = GUI(opt)
  File "/local_home/yangxingyi/3dgs/lib/python3.8/site-packages/kiui/render.py", line 43, in __init__
    if not opt.force_cuda_rast and (self.wogui or os.name == 'nt'):
AttributeError: 'Namespace' object has no attribute 'force_cuda_rast'
```

**Comment by ashawkey** [comment]
@Adamdad Thanks! This has been fixed in https://github.com/ashawkey/kiuikit/commit/ea3b152d5f4452d5dc62b624c83b8aa99bebc2dc
